apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bhs-application
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: bhs-dependency
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/application/bhs
  prune: true
  #validation: client
  healthChecks:  
    - apiVersion: networking.istio.io/v1beta1 
      kind: Gateway
      name: web-gw
      namespace: bhs-orthweb
    - apiVersion: networking.istio.io/v1beta1 
      kind: Gateway
      name: dcm-gw
      namespace: bhs-orthweb
    - apiVersion: apps/v1
      kind: Deployment
      name: orthanc
      namespace: bhs-orthweb
