apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-base
spec:
  releaseName: istio-base 
  chart:
    spec:
      chart: base 
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: "1.20.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istiod
spec:
  releaseName: istiod 
  chart:
    spec:
      chart: istiod 
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: "1.20.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    meshConfig:
      accessLogFile: /dev/stdout
      outboundTrafficPolicy:
        mode: REGISTRY_ONLY
